services:
  api:
    # Use prebuilt image from GHCR (set GHCR_OWNER in .env)
    image: ghcr.io/${GHCR_OWNER}/lostandfound-api:latest
    # For local builds instead of pulling from GHCR, comment the image line above
    # and uncomment the build block below:
    # build:
    #   context: .
    #   dockerfile: backend/LostAndFound.Api/Dockerfile
    container_name: lostandfound-api
    env_file:
      - backend/.env.production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      # Bind via env to the internal postgres service 'db'
      # Use external PostgreSQL host (set EXTERNAL_DB_HOST and POSTGRES_* in root .env)
      ConnectionStrings__DefaultConnection: Host=${EXTERNAL_DB_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};SSL Mode=Disable
    restart: unless-stopped
    networks:
      - proxy

  frontend:
    image: ghcr.io/${GHCR_OWNER}/lostandfound-frontend:latest
    container_name: lostandfound-frontend
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: ${PROXY_NETWORK}
    external: true
