services:
  api:
    image: ghcr.io/${GHCR_OWNER}/lostandfound-api:latest
    container_name: lostandfound-api
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ConnectionStrings__DefaultConnection: Host=${EXTERNAL_DB_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};SSL Mode=Disable
      Jwt__Secret: ${JWT__SECRET}
    restart: unless-stopped
    networks:
      - proxy

  frontend:
    image: ghcr.io/${GHCR_OWNER}/lostandfound-frontend:latest
    container_name: lostandfound-frontend
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: ${PROXY_NETWORK}
    external: true
